# Application Configuration
app:
  name: "Visual Product Matcher"
  debug: false
  host: "0.0.0.0"
  port: 5000
  secret_key: "change-this-in-production-use-env-var"

# Upload Configuration
upload:
  max_file_size_mb: 10
  allowed_extensions: ["jpg", "jpeg", "png", "webp"]
  upload_folder: "data/uploads"
  temp_folder: "data/temp"
  # Automatic cleanup settings for uploaded files
  cleanup:
    enabled: true
    interval_minutes: 30  # How often to run cleanup
    max_age_minutes: 60   # Delete files older than this

# ML/AI Configuration
ml:
  clip_model: "ViT-B/32"  # CLIP model variant
  device: "cuda"  # "cpu" or "cuda" - will auto-fallback to CPU if CUDA unavailable
  embedding_dimension: 512
  batch_size: 128  # Increased for better GPU utilization (RTX 3050 4GB can handle it)

# Search Configuration
search:
  default_k: 20  # Number of results to return
  min_similarity_threshold: 0.0
  max_similarity_threshold: 1.0
  default_similarity_threshold: 0.3

# Database Configuration
database:
  type: "sqlite"
  path: "data/products.db"
  echo: false

# Index Configuration
index:
  faiss_index_path: "data/index/products.index"
  embeddings_cache_path: "data/embeddings/products.npy"
  metadata_cache_path: "data/embeddings/metadata.json"
  rebuild_on_startup: false

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file: "logs/app.log"

# Performance Configuration
performance:
  cache_enabled: true
  cache_size_mb: 100
  preload_embeddings_on_startup: true

# Product Data Configuration
products:
  images_directory: "."  # Serve from project root since DB paths include full relative path
  supported_formats: ["jpg", "jpeg", "png", "webp"]

# Security & Rate Limiting Configuration
security:
  # Rate limiting (requests per time window)
  rate_limit:
    enabled: true
    default: "100 per hour"  # Global rate limit
    upload: "10 per minute"  # File upload endpoint
    search: "30 per minute"  # Search endpoints
    storage_uri: "memory://"  # Use "redis://localhost:6379" for production
  
  # File upload safety
  upload_safety:
    max_file_size_mb: 10
    scan_for_malware: false  # Set to true when antivirus integration available
    allowed_mime_types: ["image/jpeg", "image/jpg", "image/png", "image/webp"]
    strip_exif: true  # Remove EXIF data for privacy
  
  # Request validation
  request_validation:
    max_url_length: 2048
    url_timeout_seconds: 10
    allowed_url_schemes: ["http", "https"]
    blocked_private_ips: true  # Prevent SSRF attacks
  
  # Response headers
  headers:
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"
    x_xss_protection: "1; mode=block"
    strict_transport_security: "max-age=31536000; includeSubDomains"
