services:
  - type: web
    name: visual-product-matcher
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_ENV
        value: production
      - key: ML_DEVICE
        value: cpu
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /api/health
